"""Two installs of munim is a permanent keychain prompt, and nothing said so.

macOS files a keychain access rule per item per binary. The interpreter that
stores a credential reads it back with no prompt, so one install never asks for
anything. Two installs is a different condition entirely: each is a separate
binary to the keychain, so each asks approval for every item the other created,
and neither ever inherits the other's.

It took an external review and a long detour to find that, from the outside,
because the symptom is a password box and the cause is two paths. This is the
five-line check that would have said it.
"""

import pytest

from munim import doctor


@pytest.fixture(autouse=True)
def _on_a_mac(monkeypatch):
    monkeypatch.setattr(doctor.platform, "system", lambda: "Darwin")


def test_one_interpreter_is_reported_as_fine(monkeypatch):
    monkeypatch.setattr(doctor, "_mcp_command", lambda: "/opt/x/bin/munim-mcp")
    monkeypatch.setattr(doctor, "_interpreter_of", lambda s: "/opt/py/bin/python3.12")
    monkeypatch.setattr(doctor.os.path, "realpath", lambda p: "/opt/py/bin/python3.12")

    found = doctor._one_interpreter()
    assert [f.status for f in found] == [doctor.OK]


def test_two_interpreters_are_reported_with_the_command_to_fix_it(monkeypatch):
    """The other direction, which is what makes the test above mean anything."""
    monkeypatch.setattr(doctor, "_mcp_command", lambda: "/repo/.venv/bin/munim-mcp")
    monkeypatch.setattr(doctor, "_interpreter_of", lambda s: "/uv/python3.13")
    monkeypatch.setattr(doctor.os.path, "realpath", lambda p: "/brew/python3.12")

    found = doctor._one_interpreter()
    assert [f.status for f in found] == [doctor.WARN]
    assert "keychain" in found[0].detail
    assert "claude mcp add munim" in found[0].fix, \
        "a warning with no next step is a complaint"


def test_nothing_is_said_off_macos(monkeypatch):
    """Secret Service and Windows Credential Manager have no per-item,
    per-binary rule, so a mismatch there costs nothing and reporting it would
    be noise on the two platforms that do not have the problem."""
    monkeypatch.setattr(doctor.platform, "system", lambda: "Linux")
    monkeypatch.setattr(doctor, "_mcp_command", lambda: "/repo/.venv/bin/munim-mcp")
    monkeypatch.setattr(doctor, "_interpreter_of", lambda s: "/somewhere/else")
    assert doctor._one_interpreter() == []


def test_nothing_is_said_when_there_is_no_registration(monkeypatch):
    """An unregistered server is _mcp_registered's finding to report, not this
    one's. Two findings for one fact is how a report becomes unreadable."""
    monkeypatch.setattr(doctor, "_mcp_command", lambda: "")
    assert doctor._one_interpreter() == []


def test_an_unreadable_command_is_not_guessed_at(monkeypatch):
    monkeypatch.setattr(doctor, "_mcp_command", lambda: "/gone/munim-mcp")
    monkeypatch.setattr(doctor, "_interpreter_of", lambda s: "")
    assert doctor._one_interpreter() == []


def test_the_interpreter_is_read_from_the_shebang(tmp_path):
    """A console script names its Python on the first line, which is the only
    thing that says which binary the keychain will see.

    Asserted against this interpreter rather than a literal path. The first
    version wrote `#!/usr/bin/python3` and expected the answer to end in
    "python3", which passed on a Mac and failed on the CI runner, where that
    name is a symlink to python3.12 and this function resolves symlinks. That
    resolution is the point of the function, so the test has to be written in
    terms of it.
    """
    import sys

    script = tmp_path / "munim-mcp"
    script.write_text(f"#!{sys.executable} -E\n# generated by pip\n")
    assert doctor._interpreter_of(str(script)) == doctor.os.path.realpath(sys.executable)


def test_a_symlinked_interpreter_resolves_to_the_real_one(tmp_path):
    """Why it resolves at all: a pipx or uv venv symlinks to a real Python
    rather than copying it, and the resolved binary is the one macOS files its
    keychain rule against. Comparing the symlink paths would report two
    installs sharing an interpreter as a mismatch."""
    import sys

    link = tmp_path / "python-link"
    link.symlink_to(sys.executable)
    script = tmp_path / "munim-mcp"
    script.write_text(f"#!{link}\n")
    assert doctor._interpreter_of(str(script)) == doctor.os.path.realpath(sys.executable)


def test_a_script_without_a_shebang_yields_nothing(tmp_path):
    script = tmp_path / "munim-mcp"
    script.write_text("not a script\n")
    assert doctor._interpreter_of(str(script)) == ""
